"""empty message

Revision ID: 344d6c82357f
Revises: 8c850c0b4b17
Create Date: 2021-04-11 15:39:13.632429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344d6c82357f'
down_revision = '8c850c0b4b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
