"""empty message

Revision ID: 407fbcbfa8a0
Revises: 74012915fb3f
Create Date: 2021-05-29 17:39:29.637342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407fbcbfa8a0'
down_revision = '74012915fb3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'featured_image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('featured_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
