"""empty message

Revision ID: 4799c65ade39
Revises: 407fbcbfa8a0
Create Date: 2021-05-29 17:43:53.842226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4799c65ade39'
down_revision = '407fbcbfa8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('featured_image_aws_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'featured_image_aws_url')
    # ### end Alembic commands ###
