"""empty message

Revision ID: 481cdb7b50c7
Revises: b3ed99bb99a6
Create Date: 2021-05-25 19:44:37.859232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481cdb7b50c7'
down_revision = 'b3ed99bb99a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_categories',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_categories')
    # ### end Alembic commands ###
