"""empty message

Revision ID: 5eb5a7f572db
Revises: d73b29739949
Create Date: 2021-05-07 19:37:49.766856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb5a7f572db'
down_revision = 'd73b29739949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('stripe_payment_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'stripe_payment_id')
    # ### end Alembic commands ###
