"""empty message

Revision ID: 74012915fb3f
Revises: 5eb5a7f572db
Create Date: 2021-05-29 17:27:02.433237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74012915fb3f'
down_revision = '5eb5a7f572db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('featured_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'featured_image_url')
    # ### end Alembic commands ###
