"""empty message

Revision ID: 8004e4327a71
Revises: 8c850c0b4b17
Create Date: 2021-04-10 17:51:07.758350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8004e4327a71'
down_revision = '8c850c0b4b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('money_needed', sa.Float(), nullable=True),
    sa.Column('people_needed', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('published', 'draft', name='projectstatusenum'), server_default='draft', nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
