"""empty message

Revision ID: d73b29739949
Revises: ccf50603cd02
Create Date: 2021-04-24 16:18:47.479149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73b29739949'
down_revision = 'ccf50603cd02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'people_needed',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'people_needed',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
